import { Project } from "@/types/project";

export const projects: Project[] = [
  // Row 1: rectangle, square
  {
    slug: "panmure-liberum",
    title: "Panmure Liberum",
    subtitle: "Website redesign and build",
    heroImage: "/images/PanmureLiberum/Asset 1@3x-8.png",
    detailsVideo: "/images/PanmureLiberum/Hero.mov",
    detailsMediaType: "desktop",
    problem: "Panmure Liberum needed a clearer digital presence that better reflected its position in investment banking and made its offering easier for clients to understand.",
    detailsTitle: "Panmure Liberum",
    detailsSubtitle: "Website redesign and build",
    detailsText: "I was contracted by Panmure Liberum to lead the complete rebuild of their custom-coded website. The goal was to present their offering more clearly and bring the brand in line with their position in investment banking. The redesign keeps the site simple and direct, making their services easier to understand while improving the readability and scannability of the content.",
    caseStudySections: [
      {
        id: "nav",
        title: "Clear navigation",
        text: "The first priority was making the site easier to understand at a glance. A simpler navigation structure helps visitors orient themselves quickly and get to the right area without unnecessary friction.",
        mediaType: "video",
        mediaSrc: "/images/PanmureLiberum/Nav.mov",
        mediaAlt: "Panmure Liberum navigation menu",
        caption: "A simpler top-level structure",
      },
      {
        id: "services",
        title: "Service breakdown",
        text: "The services needed to be separated and explained more clearly. Breaking them into distinct cards gives visitors a quicker sense of the business and how the offering is organised.",
        mediaType: "video",
        mediaSrc: "/images/PanmureLiberum/Service%20break.mov",
        mediaAlt: "Panmure Liberum service cards",
        caption: "A clearer breakdown of the offer",
      },
      {
        id: "tabs",
        title: "Faster scanning",
        text: "Tabbed service pages reduce the need for long scrolling and let users jump directly to the information most relevant to them. That makes the content easier to scan and less tiring to navigate.",
        mediaType: "video",
        mediaSrc: "/images/PanmureLiberum/Tabs2.mov",
        mediaAlt: "Panmure Liberum service tabs",
        caption: "Tabs help users find information faster",
      },
      {
        id: "map",
        title: "Execution capability",
        text: "The map component helps communicate the firm’s execution capability in a more immediate visual way. It adds substance to the story without making the page feel heavier.",
        mediaType: "video",
        mediaSrc: "/images/PanmureLiberum/Map.mov",
        mediaAlt: "Panmure Liberum map component",
        caption: "A visual way to show execution reach",
      },
    ],
    caseStudyTextSections: [
      {
        id: "research",
        title: "Mapping user needs",
        text: "The process began by looking at what prospective clients actually needed from the site: a faster way to understand the firm, its services, and its credibility. That meant reducing ambiguity and making the site easier to navigate at a glance.",
      },
      {
        id: "structure",
        title: "Breaking down services",
        text: "A key part of the redesign was separating and restructuring the service offering. The aim was to make each area of the business easier to understand on its own while still feeling part of one coherent whole.",
      },
      {
        id: "constraints",
        title: "Design constraints",
        text: "The site needed to feel more considered and more aligned with the status of the business, without becoming visually overworked. That led to a restrained system with clearer hierarchy, stronger spacing, and a sharper focus on readability.",
      },
      {
        id: "build",
        title: "Componentising and build",
        text: "The project then moved into componentising the interface and building the site in code. That helped keep the system consistent and made it easier to transfer the work into Umbraco in a way that remained maintainable.",
      },
    ],
    gallery: [],
  },
  {
    slug: "learnllama",
    title: "LearnLlama.",
    subtitle: "Winner of the Best AR Project at Goldsmiths University",
    heroImage: "/images/LearnLlamaHome.png",
    detailsVideo: "/images/LearnLlama/ScreenRecording_12-09-2024%2020-05-54_1.MP4",
    detailsMediaType: "tablet",
    problem: "Textbooks can be a difficult way to learn for children who need a more physical, visual, or interactive way into the material. When learning is locked into dense pages of text, kinesthetic learners are often left behind.",
    detailsTitle: "LearnLlama",
    detailsSubtitle: "Bringing textbooks to life",
    detailsText: "LearnLlama is an AR study companion designed to make textbook learning more accessible for children who struggle with text-heavy material. By scanning illustrations in a book, students can trigger interactive 3D models, explore them through touch, and read or listen to supporting explanations inside the same experience.",
    caseStudySections: [
      {
        id: "language",
        title: "Friendly language",
        text: "The interface was designed to feel approachable and playful rather than overly technical. Rounded forms, simple controls, and a lighter visual language help position the app as a study companion for children rather than a rigid school tool.",
        mediaType: "image",
        mediaSrc: "/images/LearnLlama/1.png",
        mediaAlt: "LearnLlama interface showing its friendly design language",
        caption: "A playful and approachable interface",
      },
      {
        id: "scan",
        title: "Scan to trigger AR",
        text: "Children scan an illustration in the textbook to trigger a 3D model using AR image tracking. That connection between the printed page and the digital layer makes the learning experience feel immediate and much easier to grasp.",
        mediaType: "image",
        mediaSrc: "/images/LearnLlama/2.png",
        mediaAlt: "LearnLlama using AR image tracking to trigger a 3D model",
        caption: "Textbook illustrations trigger AR content",
      },
      {
        id: "touch",
        title: "Touch the model",
        text: "Once the model appears, students can interact with it directly through touch. Different parts of the model can be selected, making the experience more active and helping learners build understanding through exploration rather than passive reading.",
        mediaType: "image",
        mediaSrc: "/images/LearnLlama/3.png",
        mediaAlt: "LearnLlama interactive 3D model with touch-based exploration",
        caption: "Touch interaction makes the model explorable",
      },
      {
        id: "read-listen",
        title: "Read or listen",
        text: "Each part of the model can reveal more explanation, with the option to read the information or listen to it through audio. This gives children different ways into the same topic and helps support a wider range of learning styles.",
        mediaType: "image",
        mediaSrc: "/images/LearnLlama/4.jpg",
        mediaAlt: "LearnLlama showing additional information and audio support",
        caption: "More detail with optional audio support",
      },
    ],
    caseStudyTextSections: [
      {
        id: "challenge",
        title: "The challenge",
        text: "Textbooks can be a difficult place for kinesthetic learners. The content may be there, but the format often asks children to sit still, read heavily, and imagine concepts without much support from interaction or feedback.",
      },
      {
        id: "sprint",
        title: "Four-week sprint",
        text: "During a four-week design sprint, I designed and developed LearnLlama as an AR study companion that could sit alongside a physical textbook. The aim was to create a more intuitive way for children to move between reading, seeing, and interacting with the material.",
      },
      {
        id: "product",
        title: "Designing the companion",
        text: "The product combined image tracking, 3D content, touch interaction, and short supporting explanations so that textbook diagrams could become something students could actively explore. That made the learning experience feel less abstract and more responsive to the learner.",
      },
      {
        id: "outcome",
        title: "The outcome",
        text: "The final outcome was a playful AR study companion that made textbook content easier to access through interaction. The project went on to win the Best AR Project award at Goldsmiths.",
      },
    ],
    gallery: [
      "/images/LearnLlama/Image1.1.png",
      "/images/LearnLlama/Image2.2.png",
      "/images/LearnLlama/Image3.1.png",
      "/images/LearnLlama/Image4.png",
    ],
  },
  // Row 2: square, rectangle
  {
    slug: "donkeyjobs",
    title: "DonkeyJobs",
    subtitle: "Eco friendly home maintenance based in South London",
    heroImage: "/images/DonkeyjobsHome.png",
    problem: "Traditional garden maintenance is often expensive, noisy, and reliant on fuel-powered tools and vans. This makes it less accessible for customers and far from environmentally friendly. We needed a way to deliver high-quality garden care while reducing costs, emissions, and disruption, without compromising on reliability.",
    detailsTitle: "DonkeyJobs",
    detailsSubtitle: "Eco Friendly Home Maintenance",
    detailsText: "I founded and managed DonkeyJobs, a garden-maintenance company based in South London. What started as a small COVID project grew into a fully-operational, eco-friendly service using cargo bikes and electric tools for every job. Over the four years, DonkeyJobs worked with more than 1,000 clients, grew a team of 20+ people, and gained over 20 million views on TikTok. I led the website, branding, marketing, and hiring while helping shape the overall service model.",
    gallery: [
      "/images/Donkeyjobs/Window cleaning.png",
      "/images/Donkeyjobs/image1.jpeg",
      "/images/Donkeyjobs/Image2.jpg",
      "/images/Donkeyjobs/Donkeyjobs.png",
      "/images/Donkeyjobs/Screenshot 2025-12-03 at 11.18.19.png"
    ],
  },
  {
    slug: "recanvased",
    title: "reCanvased",
    subtitle: "Helping unknown artists break out into the art world with AR",
    heroImage: "/images/RecanvasedHome.png",
    detailsVideo: "/images/Recanvased/ScreenRecording_07-29-2025%2017.MP4",
    detailsMediaType: "phone",
    problem: "Buying art should feel exciting, but for many people it feels stressful. Without knowing if a piece will fit, suit their space, or feel 'right', they hesitate — or don't buy at all. The uncertainty around visualising artwork makes the experience harder than it needs to be.",
    whyItMatters: "Art is personal, expensive, and tied to the atmosphere of a home. When buyers cannot judge scale or context, they postpone decisions, and emerging artists lose the sale before the work has really been considered.",
    theIdea: "reCanvased pairs a React Native browsing app with an AR companion built in Unity, so people can preview artworks on their own walls and feel confident before they commit.",
    detailsTitle: "reCanvased",
    detailsSubtitle: "Visualize art in your home",
    detailsText: "ReCanvased is a project exploring how digital tools can help people visualise art before buying it. I built a cross-platform browsing app in React Native and an AR visualisation companion in Unity that lets users preview artwork directly on their walls. The project was awarded a Distinction as my final Master’s submission.",
    caseStudySections: [
      {
        id: "browse",
        title: "Browse and save",
        text: "Users can browse available work, look more closely at individual pieces, save favourites, and move through the app in a way that feels familiar and easy to scan.",
        mediaType: "image",
        mediaSrc: "/images/Recanvased/Recanvased1.PNG",
        mediaAlt: "ReCanvased browsing and product flow",
        caption: "Marketplace browsing and saved pieces",
      },
      {
        id: "preview",
        title: "Open AR view",
        text: "From the artwork page, users can move directly into AR to stop imagining the piece abstractly and start viewing it in the context of a real room.",
        mediaType: "image",
        mediaSrc: "/images/Recanvased/Recanvased2.PNG",
        mediaAlt: "ReCanvased artwork detail page with see in your space action",
        caption: "From artwork page to AR view",
      },
      {
        id: "place",
        title: "Place on wall",
        text: "Once inside AR, users tap a wall to position the selected work. This makes questions of scale, placement, and fit much easier to judge.",
        mediaType: "image",
        mediaSrc: "/images/Recanvased/Recanvased3.PNG",
        mediaAlt: "ReCanvased AR placement interface on a wall",
        caption: "Position the work directly in the room",
      },
      {
        id: "compare",
        title: "Compare in room",
        text: "Users can place multiple works to compare scale, spacing, and how different pieces sit together before deciding what feels right.",
        mediaType: "image",
        mediaSrc: "/images/Recanvased/Recanvased4.PNG",
        mediaAlt: "ReCanvased multi-artwork AR comparison state",
        caption: "Compare pieces at room scale",
      },
    ],
    caseStudyTextSections: [
      {
        id: "problem",
        title: "The problem",
        text: "Buying art is a high-friction decision. People may like a piece in isolation, but they still struggle to imagine its scale, how it will sit on a wall, or whether it will suit the mood of a room. That uncertainty often leads to hesitation rather than purchase.",
      },
      {
        id: "approach",
        title: "The approach",
        text: "I designed ReCanvased as an end-to-end experience rather than just an artwork marketplace. The browsing app and the AR placement flow were built to work as one journey, so the transition from discovery to decision felt natural rather than bolted on.",
      },
      {
        id: "solution",
        title: "The solution",
        text: "The core idea was to let users move from viewing a piece on a product page to placing it directly on their own wall. By grounding the decision in the actual room, the app could reduce uncertainty and make the purchase feel more confident and informed.",
      },
      {
        id: "outcome",
        title: "The outcome",
        text: "The final project became a clearer proposition about confidence in buying art, not just browsing it. It brought together marketplace browsing, artist listing, and AR visualisation into one coherent system, and it was awarded a Distinction as my final Master’s submission.",
      },
    ],
    gallery: [
      { src: "/images/Recanvased/RecanvasedVid1.MOV", label: "Scroll the gallery to explore everything quickly" },
      { src: "/images/Recanvased/RecanvasedVid2.MOV", label: "Zoom in for a closer look at the details" },
      { src: "/images/Recanvased/RecanvasedVid3.MOV", label: "See each piece in\nyour own space for context" },
      { src: "/images/Recanvased/RecanvasedVid4.MOV", label: "Add multiple artworks at scale to plan a wall" },
    ],
  },
  {
    slug: "signal",
    title: "Signal",
    subtitle: "A simple to-do list that's surprisingly powerful",
    heroImage: "/images/Signal/Signalthumbnail.png",
    detailsVideo: "/images/Signal/ScreenRecording_12-01-2025%2016-43-40_1.MP4",
    detailsMediaType: "phone",
    problem: "Buying art should feel exciting, but for many people it feels stressful. Without knowing if a piece will fit, suit their space, or feel 'right', they hesitate — or don't buy at all. The uncertainty around visualising artwork makes the experience harder than it needs to be.",
    detailsTitle: "Signal",
    detailsSubtitle: "Gesture-driven task management",
    detailsText: "Signal is a gesture-based to-do list that removes visual clutter from task management. I wanted to avoid checkboxes, heavy UI, and endless menus, and instead build a system that lets people separate the signal from the noise. Signal supports deeply nested lists, clean organisation, and almost no visible buttons—everything is driven through simple gestures for a focused writing experience.",
    gallery: [
      { src: "/images/Signal/Video1.MOV", label: "Gesture-based to-do list" },
      { src: "/images/Signal/Video2.mov", label: "Repeat lists for everyday use" },
      { src: "/images/Signal/Video3.mov", label: "Dark mode" },
      { src: "/images/Signal/clip4.mp4", label: "Notes mode" },
    ],
  },
  {
    slug: "canopy-of-echos",
    title: "Canopy of Echos",
    subtitle: "Best Heritage Narrative Prize · Nanjing Digital Heritage Hackathon",
    heroImage: "/images/CanopyOfEchos/Demo1.PNG",
    problem: "This is a placeholder problem statement for canopy of echos.",
    detailsTitle: "Canopy of Echos",
    detailsSubtitle: "An interactive sculpture displaying ancient artifacts",
    detailsText: "Canopy of Echos is a kinetic, light-based sculpture created for the 2025 Nanjing Digital Heritage Hackathon. Inspired by fragments of physical and cultural memory, the installation uses moving \"stones\" and responsive lighting to echo the stories of local citizens. The project was awarded the Best Heritage Narrative Prize at the hackathon.",
    gallery: [
      "/images/CanopyOfEchos/CanopyOfEchosAWard.jpg",
      "/images/CanopyOfEchos/IMG_2707.PNG",
      "/images/CanopyOfEchos/Demo2.png",
      "/images/CanopyOfEchos/Screenshot%202025-08-12%20220723.png",
      "/images/CanopyOfEchos/%E6%95%88%E6%9E%9C%E5%9B%BE1%201.png",
    ],
  },
];
