import { Project } from "@/types/project";

export const projects: Project[] = [
  // Row 1: rectangle, square
  {
    slug: "recanvased",
    title: "reCanvased",
    subtitle: "Helping unknown artists break out into the art world with AR",
    heroImage: "/images/RecanvasedHome.png",
    detailsVideo: "/images/Recanvased/ScreenRecording_07-29-2025%2017.MP4",
    problem: "Buying art should feel exciting, but for many people it feels stressful. Without knowing if a piece will fit, suit their space, or feel 'right', they hesitate — or don't buy at all. The uncertainty around visualising artwork makes the experience harder than it needs to be.",
    detailsTitle: "reCanvased",
    detailsSubtitle: "Visualize art in your home",
    detailsText: "ReCanvased is a project exploring how digital tools can help people visualise art before buying it. I built a cross-platform browsing app in React Native and an AR visualisation companion in Unity that lets users preview artwork directly on their walls. The project was awarded a Distinction as my final Master’s submission.",
    gallery: [
      { src: "/images/Recanvased/RecanvasedVid1.MOV", label: "Scroll the gallery to explore everything quickly" },
      { src: "/images/Recanvased/RecanvasedVid2.MOV", label: "Zoom in for a closer look at the details" },
      { src: "/images/Recanvased/RecanvasedVid3.MOV", label: "See each piece in\nyour own space for context" },
      { src: "/images/Recanvased/RecanvasedVid4.MOV", label: "Add multiple artworks at scale to plan a wall" },
    ],
  },
  {
    slug: "learnllama",
    title: "LearnLlama.",
    subtitle: "Winner of the Best AR Project at Goldsmiths University",
    heroImage: "/images/LearnLlamaHome.png",
    detailsVideo: "/images/LearnLlama/ScreenRecording_12-09-2024%2020-05-54_1.MP4",
    problem: "Buying art should feel exciting, but for many people it feels stressful. Without knowing if a piece will fit, suit their space, or feel 'right', they hesitate — or don't buy at all. The uncertainty around visualising artwork makes the experience harder than it needs to be.",
    detailsTitle: "LearnLlama",
    detailsSubtitle: "Bringing textbooks to life",
    detailsText: "LearnLlama is an educational companion designed to make textbooks more engaging. Children can scan illustrations to reveal interactive 3D models and explanations, making learning more accessible for those who struggle with text-heavy material. The aim was to bring traditional books into a more intuitive, playful digital space.",
    gallery: [
      "/images/LearnLlama/Image1.1.png",
      "/images/LearnLlama/Image2.2.png",
      "/images/LearnLlama/Image3.1.png",
      "/images/LearnLlama/Image4.png",
    ],
  },
  // Row 2: rectangle, square
  {
    slug: "donkeyjobs",
    title: "DonkeyJobs",
    subtitle: "Eco friendly home maintenance based in South London",
    heroImage: "/images/DonkeyjobsHome.png",
    problem: "Traditional garden maintenance is often expensive, noisy, and reliant on fuel-powered tools and vans. This makes it less accessible for customers and far from environmentally friendly. We needed a way to deliver high-quality garden care while reducing costs, emissions, and disruption, without compromising on reliability.",
    detailsTitle: "DonkeyJobs",
    detailsSubtitle: "Eco Friendly Home Maintenance",
    detailsText: "I founded and managed DonkeyJobs, a garden-maintenance company based in South London. What started as a small COVID project grew into a fully-operational, eco-friendly service using cargo bikes and electric tools for every job. Over the four years, DonkeyJobs worked with more than 1,000 clients, grew a team of 20+ people, and gained over 20 million views on TikTok. I led the website, branding, marketing, and hiring while helping shape the overall service model.",
    gallery: [
      "/images/Donkeyjobs/Window cleaning.png",
      "/images/Donkeyjobs/image1.jpeg",
      "/images/Donkeyjobs/Image2.jpg",
      "/images/Donkeyjobs/Donkeyjobs.png",
      "/images/Donkeyjobs/Screenshot 2025-12-03 at 11.18.19.png"
    ],
  },
  {
    slug: "canopy-of-echos",
    title: "Canopy of Echos",
    subtitle: "Best Heritage Narrative Prize · Nanjing Digital Heritage Hackathon",
    heroImage: "/images/CanopyOfEchos/Demo1.PNG",
    problem: "This is a placeholder problem statement for canopy of echos.",
    detailsTitle: "Canopy of Echos",
    detailsSubtitle: "An interactive sculpture displaying ancient artifacts",
    detailsText: "Canopy of Echos is a kinetic, light-based sculpture created for the 2025 Nanjing Digital Heritage Hackathon. Inspired by fragments of physical and cultural memory, the installation uses moving \"stones\" and responsive lighting to echo the stories of local citizens. The project was awarded the Best Heritage Narrative Prize at the hackathon.",
    gallery: [
      "/images/CanopyOfEchos/CanopyOfEchosAWard.jpg",
      "/images/CanopyOfEchos/IMG_2707.PNG",
      "/images/CanopyOfEchos/Demo2.png",
      "/images/CanopyOfEchos/Screenshot%202025-08-12%20220723.png",
      "/images/CanopyOfEchos/%E6%95%88%E6%9E%9C%E5%9B%BE1%201.png",
    ],
  },
  // Row 3: rectangle, square
  {
    slug: "signal",
    title: "Signal",
    subtitle: "A simple to-do list that's surprisingly powerful",
    heroImage: "/images/Signal/Signalthumbnail.png",
    detailsVideo: "/images/Signal/ScreenRecording_12-01-2025%2016-43-40_1.MP4",
    problem: "Buying art should feel exciting, but for many people it feels stressful. Without knowing if a piece will fit, suit their space, or feel 'right', they hesitate — or don't buy at all. The uncertainty around visualising artwork makes the experience harder than it needs to be.",
    detailsTitle: "Signal",
    detailsSubtitle: "Gesture-driven task management",
    detailsText: "Signal is a gesture-based to-do list that removes visual clutter from task management. I wanted to avoid checkboxes, heavy UI, and endless menus, and instead build a system that lets people separate the signal from the noise. Signal supports deeply nested lists, clean organisation, and almost no visible buttons—everything is driven through simple gestures for a focused writing experience.",
    gallery: [
      { src: "/images/Signal/Video1.MOV", label: "Gesture-based to-do list" },
      { src: "/images/Signal/Video2.mov", label: "Repeat lists for everyday use" },
      { src: "/images/Signal/Video3.mov", label: "Dark mode" },
      { src: "/images/Signal/clip4.mp4", label: "Notes mode" },
    ],
  },
  {
    slug: "gallery",
    title: "Gallery",
    subtitle: "Selected artwork sketches",
    heroImage: "/images/Gallery/oodoHome.png",
    problem: "A simple gallery of sketches and artwork explorations.",
    detailsTitle: "Gallery",
    detailsSubtitle: "Full-size explorations",
    detailsText: "Swipe through the series for a closer look at the process pieces and experiments that inform my product work.",
    gallery: [
      "/images/Gallery/oodoHome.png",
      "/images/Gallery/CarVideo%202.mp4",
      "/images/Gallery/AloneVideo%202.mp4",
      "/images/Gallery/Lawny-Screenshot3.png",
      "/images/Gallery/FiftypenceAward.png",
      "/images/Gallery/Screenshot%202025-12-04%20at%2009.13.25.png",
      "/images/Gallery/Lotus1.png",
      "/images/Gallery/Sketch1.jpg",
      "/images/Gallery/Sketch3.jpg",
      "/images/Gallery/Sketch2.jpg",
      "/images/Gallery/Sketch4.jpg",
      "/images/Gallery/Sketch.jpg",
      "/images/Gallery/Sketch5.jpg",
      "/images/Gallery/Sketch6.jpg",
    ],
  },
];

