import { Project } from "@/types/project";

export const projects: Project[] = [
  // Row 1: rectangle, square
  {
    slug: "panmure-liberum",
    title: "Panmure Liberum",
    subtitle: "Website redesign and build",
    heroImage: "/images/PanmureLiberum/panmure-thumbnail.png",
    detailsVideo: "/images/PanmureLiberum/hero.mp4",
    detailsMediaType: "desktop",
    pageStyle: "editorial",
    caseStudyDepth: "feature",
    projectDiscipline: "Digital experience",
    projectServices: "Strategy · UX/UI · Front-end build",
    editorialStatement: "Reframing a complex financial offer as a clear, confident digital experience.",
    outcome: "A clearer website built from reusable components, designed to make a complex business easier to understand.",
    editorialPalette: {
      page: "#F1EDE5",
      surface: "#FAF8F3",
      soft: "#E5E1D8",
      primary: "#153D29",
      onPrimary: "#F5F1E9",
      accent: "#CBD6C8",
      onAccent: "#153D29",
      ink: "#242422",
      mediaField: "#E5E1D8",
    },
    problem: "Panmure Liberum needed a clearer digital presence that better reflected its position in investment banking and made its offering easier for clients to understand.",
    detailsTitle: "Panmure Liberum",
    detailsSubtitle: "Website redesign and build",
    detailsText: "I was contracted to lead the end-to-end redesign and front-end build of Panmure Liberum’s custom-coded website, translating a complex financial offer into a clearer and more confident digital experience.",
    caseStudySections: [
      {
        id: "nav",
        title: "Clear navigation",
        text: "A simplified top-level structure helps visitors understand the business and reach the right service faster.",
        mediaType: "video",
        mediaSrc: "/images/PanmureLiberum/nav.mp4",
        mediaAlt: "Panmure Liberum navigation menu",
        caption: "A simpler top-level structure",
      },
      {
        id: "services",
        title: "Service breakdown",
        text: "Four distinct service routes make the firm’s offer legible at a glance.",
        mediaType: "video",
        mediaSrc: "/images/PanmureLiberum/service-break.mp4",
        mediaAlt: "Panmure Liberum service cards",
        caption: "A clearer breakdown of the offer",
      },
      {
        id: "tabs",
        title: "Faster scanning",
        text: "Tabbed pages let users move directly to relevant information without working through long blocks of copy.",
        mediaType: "video",
        mediaSrc: "/images/PanmureLiberum/tabs.mp4",
        mediaAlt: "Panmure Liberum service tabs",
        caption: "Tabs help users find information faster",
      },
      {
        id: "map",
        title: "Execution capability",
        text: "An interactive map turns global execution reach into something immediate and explorable.",
        mediaType: "video",
        mediaSrc: "/images/PanmureLiberum/map.mp4",
        mediaAlt: "Panmure Liberum map component",
        caption: "A visual way to show execution reach",
      },
    ],
    caseStudyTextSections: [
      {
        id: "research",
        title: "Mapping user needs",
        text: "I mapped what prospective clients needed from the site: a fast way to understand the firm, its services, and its credibility.",
      },
      {
        id: "structure",
        title: "Breaking down services",
        text: "I separated and restructured the service offer so each area could stand alone while remaining part of one coherent whole.",
      },
      {
        id: "constraints",
        title: "Design constraints",
        text: "A restrained visual system uses clearer hierarchy, stronger spacing, and disciplined typography to reflect the firm’s status.",
      },
      {
        id: "build",
        title: "Componentising and build",
        text: "I translated the interface into reusable front-end components before transferring the system into Umbraco for long-term maintenance.",
      },
    ],
    gallery: [],
  },
  {
    slug: "learnllama",
    title: "LearnLlama.",
    subtitle: "Winner of the Best AR Project at Goldsmiths University",
    heroImage: "/images/LearnLlama/learnllama-thumbnail.png",
    detailsVideo: "/images/LearnLlama/hero.mp4",
    detailsMediaType: "tablet",
    pageStyle: "editorial",
    caseStudyDepth: "feature",
    projectDiscipline: "Learning experience",
    projectServices: "Product design · AR · Unity development",
    editorialStatement: "Turning static textbook diagrams into something children can see, touch, and explore.",
    outcome: "A working AR study companion completed in four weeks and awarded Best AR Project at Goldsmiths.",
    editorialPalette: {
      page: "#F5F2E9",
      surface: "#FFF9DC",
      soft: "#F5F2E9",
      primary: "#F3D82B",
      onPrimary: "#171717",
      accent: "#CFE7F3",
      onAccent: "#171717",
      ink: "#171717",
      mediaField: "#F5F2E9",
    },
    problem: "Textbooks can be a difficult way to learn for children who need a more physical, visual, or interactive way into the material. When learning is locked into dense pages of text, kinesthetic learners are often left behind.",
    detailsTitle: "LearnLlama",
    detailsSubtitle: "Bringing textbooks to life",
    detailsText: "LearnLlama is an AR study companion designed to make textbook learning more accessible for children who struggle with text-heavy material. By scanning illustrations in a book, students can trigger interactive 3D models, explore them through touch, and read or listen to supporting explanations inside the same experience.",
    caseStudySections: [
      {
        id: "language",
        title: "Designed for young learners",
        text: "The interface uses clear language, simple controls, and strong visual hierarchy to reduce cognitive load. Each screen focuses on one action at a time, helping children explore independently without the experience feeling overly instructional.",
        mediaType: "image",
        mediaSrc: "/images/LearnLlama/1.png",
        mediaAlt: "LearnLlama interface designed for young learners",
        caption: "Simple screens designed for independent learning",
      },
      {
        id: "icon-library",
        title: "A child-friendly icon library",
        text: "I created a consistent library of illustrated icons specifically for LearnLlama. Familiar shapes and repeated visual cues help children recognise actions quickly, while giving the app its own playful identity.",
        mediaType: "image",
        mediaSrc: "/images/LearnLlama/IMG_3698.jpg",
        mediaAlt: "Custom icon library designed for the LearnLlama app",
        caption: "A custom visual system used throughout the app",
      },
      {
        id: "scan",
        title: "Scan to trigger AR",
        text: "Children scan an illustration in the textbook to trigger a 3D model using AR image tracking. That connection between the printed page and the digital layer makes the learning experience feel immediate and much easier to grasp.",
        mediaType: "image",
        mediaSrc: "/images/LearnLlama/2.png",
        mediaAlt: "LearnLlama using AR image tracking to trigger a 3D model",
        caption: "Textbook illustrations trigger AR content",
      },
      {
        id: "touch",
        title: "Touch the model",
        text: "Once the model appears, students can interact with it directly through touch. Different parts of the model can be selected, making the experience more active and helping learners build understanding through exploration rather than passive reading.",
        mediaType: "image",
        mediaSrc: "/images/LearnLlama/3.png",
        mediaAlt: "LearnLlama interactive 3D model with touch-based exploration",
        caption: "Touch interaction makes the model explorable",
      },
      {
        id: "read-listen",
        title: "Read or listen",
        text: "Each part of the model can reveal more explanation, with the option to read the information or listen to it through audio. This gives children different ways into the same topic and helps support a wider range of learning styles.",
        mediaType: "image",
        mediaSrc: "/images/LearnLlama/4.jpg",
        mediaAlt: "LearnLlama showing additional information and audio support",
        caption: "More detail with optional audio support",
      },
    ],
    caseStudyTextSections: [
      {
        id: "challenge",
        title: "The challenge",
        text: "Textbooks can be a difficult place for kinesthetic learners. The content may be there, but the format often asks children to sit still, read heavily, and imagine concepts without much support from interaction or feedback.",
      },
      {
        id: "sprint",
        title: "Four-week sprint",
        text: "During a four-week design sprint, I designed and developed LearnLlama as an AR study companion that could sit alongside a physical textbook. The aim was to create a more intuitive way for children to move between reading, seeing, and interacting with the material.",
      },
      {
        id: "product",
        title: "Designing the companion",
        text: "The product combined image tracking, 3D content, touch interaction, and short supporting explanations so that textbook diagrams could become something students could actively explore. That made the learning experience feel less abstract and more responsive to the learner.",
      },
      {
        id: "outcome",
        title: "The outcome",
        text: "The final outcome was a playful AR study companion that made textbook content easier to access through interaction. The project went on to win the Best AR Project award at Goldsmiths.",
      },
    ],
    gallery: [
      "/images/LearnLlama/Image1.1.png",
      "/images/LearnLlama/Image2.2.png",
      "/images/LearnLlama/Image3.1.png",
      "/images/LearnLlama/Image4.png",
    ],
  },
  // Row 2: square, rectangle
  {
    slug: "donkeyjobs",
    title: "DonkeyJobs",
    subtitle: "Eco friendly home maintenance based in South London",
    heroImage: "/images/Donkeyjobs/donkeyjobs-thumbnail.png",
    detailsHeroImage: "/images/Donkeyjobs/donkeyjobs-hero-new.jpg",
    detailsMediaType: "physical",
    pageStyle: "editorial",
    caseStudyDepth: "compact",
    projectDiscipline: "Service and brand",
    projectServices: "Founder · Product · Operations",
    editorialStatement: "Building an environmentally lighter home-maintenance service from the ground up.",
    outcome: "A real service used by more than 1,000 clients, supported by an operating model that grew over time.",
    editorialPalette: {
      page: "#F1ECE2",
      surface: "#F7F4EC",
      soft: "#E7EFF4",
      primary: "#2E5E78",
      onPrimary: "#F7F4EC",
      accent: "#BFD7E8",
      onAccent: "#1D2A2F",
      ink: "#1D2A2F",
      mediaField: "#E7EFF4",
    },
    problem: "Traditional garden maintenance is often expensive, noisy, and reliant on fuel-powered tools and vans. This makes it less accessible for customers and far from environmentally friendly. We needed a way to deliver high-quality garden care while reducing costs, emissions, and disruption, without compromising on reliability.",
    detailsTitle: "DonkeyJobs",
    detailsSubtitle: "Eco Friendly Home Maintenance",
    detailsText: "I founded and managed DonkeyJobs, a garden-maintenance company based in South London. What started as a small COVID project grew into a fully-operational, eco-friendly service using cargo bikes and electric tools for every job. Over four years, DonkeyJobs worked with more than 1,000 clients, developed a flexible operating team, and gained over 20 million views on TikTok. I led the website, branding, marketing, and hiring while helping shape the overall service model.",
    caseStudySections: [
      {
        id: "service",
        title: "A service designed around the street",
        text: "Cargo bikes and electric tools reduced noise, emissions, and operating costs while making it possible to move efficiently between local jobs.",
        mediaType: "image",
        frameType: "physical",
        mediaSrc: "/images/Donkeyjobs/image1.jpeg",
        mediaAlt: "DonkeyJobs team delivering garden maintenance by cargo bike",
        caption: "A practical low-emission operating model",
      },
      {
        id: "growth",
        title: "Building trust at local scale",
        text: "A clear identity, reliable service, and direct communication helped a small lockdown idea grow into a recognisable South London business.",
        mediaType: "image",
        frameType: "physical",
        mediaSrc: "/images/Donkeyjobs/Donkeyjobs.png",
        mediaAlt: "DonkeyJobs brand and service in use",
        caption: "Brand, service, and operations working together",
      },
    ],
    caseStudyTextSections: [
      {
        id: "starting-small",
        title: "Starting from scratch",
        text: "I founded DonkeyJobs during the first lockdown as a practical, local alternative to conventional garden maintenance. The early service was deliberately simple: show up reliably, do good work, and build trust one customer at a time.",
      },
      {
        id: "service-model",
        title: "Designing the service",
        text: "The business used cargo bikes and electric tools to reduce noise, emissions, and operating costs. I shaped the service model around the realities of both customers and the people doing the work, rather than treating the website as a separate marketing layer.",
      },
      {
        id: "growth",
        title: "Learning through growth",
        text: "Over four years, DonkeyJobs grew to more than 1,000 clients and developed a flexible team and operating model around the work. I led the brand, website, marketing, hiring, and day-to-day decisions, learning how people actually behave when a product becomes a real service.",
      },
    ],
    gallery: [
      "/images/Donkeyjobs/Window cleaning.png",
      "/images/Donkeyjobs/image1.jpeg",
      "/images/Donkeyjobs/Image2.jpg",
      "/images/Donkeyjobs/Donkeyjobs.png",
      "/images/Donkeyjobs/Screenshot 2025-12-03 at 11.18.19.png"
    ],
  },
  {
    slug: "recanvased",
    title: "reCanvased",
    subtitle: "Helping unknown artists break out into the art world with AR",
    heroImage: "/images/Recanvased/recanvased-thumbnail.png",
    detailsVideo: "/images/Recanvased/hero.mp4",
    detailsMediaType: "phone",
    pageStyle: "editorial",
    caseStudyDepth: "feature",
    projectDiscipline: "Product and AR",
    projectServices: "Research · UX/UI · React Native · Unity",
    editorialStatement: "Giving art buyers the confidence to move from discovery to a decision.",
    outcome: "An end-to-end marketplace and AR proposition awarded a Distinction as my final Master’s submission.",
    editorialPalette: {
      page: "#F4EFEA",
      surface: "#FFF8F3",
      soft: "#F4EFEA",
      primary: "#D95F68",
      onPrimary: "#24191A",
      accent: "#8BA8E8",
      onAccent: "#171515",
      ink: "#1F1C1C",
      mediaField: "#F4EFEA",
    },
    problem: "Buying art should feel exciting, but for many people it feels stressful. Without knowing if a piece will fit, suit their space, or feel 'right', they hesitate — or don't buy at all. The uncertainty around visualising artwork makes the experience harder than it needs to be.",
    whyItMatters: "Art is personal, expensive, and tied to the atmosphere of a home. When buyers cannot judge scale or context, they postpone decisions, and emerging artists lose the sale before the work has really been considered.",
    theIdea: "reCanvased pairs a React Native browsing app with an AR companion built in Unity, so people can preview artworks on their own walls and feel confident before they commit.",
    detailsTitle: "reCanvased",
    detailsSubtitle: "Visualize art in your home",
    detailsText: "ReCanvased is a project exploring how digital tools can help people visualise art before buying it. I built a cross-platform browsing app in React Native and an AR visualisation companion in Unity that lets users preview artwork directly on their walls. The project was awarded a Distinction as my final Master’s submission.",
    caseStudySections: [
      {
        id: "browse",
        title: "Browse and save",
        text: "Users can browse available work, look more closely at individual pieces, save favourites, and move through the app in a way that feels familiar and easy to scan.",
        mediaType: "image",
        mediaSrc: "/images/Recanvased/Recanvased1.PNG",
        mediaAlt: "ReCanvased browsing and product flow",
        caption: "Marketplace browsing and saved pieces",
      },
      {
        id: "preview",
        title: "Open AR view",
        text: "From the artwork page, users can move directly into AR to stop imagining the piece abstractly and start viewing it in the context of a real room.",
        mediaType: "image",
        mediaSrc: "/images/Recanvased/Recanvased2.PNG",
        mediaAlt: "ReCanvased artwork detail page with see in your space action",
        caption: "From artwork page to AR view",
      },
      {
        id: "place",
        title: "Place on wall",
        text: "Once inside AR, users tap a wall to position the selected work. This makes questions of scale, placement, and fit much easier to judge.",
        mediaType: "image",
        mediaSrc: "/images/Recanvased/Recanvased3.PNG",
        mediaAlt: "ReCanvased AR placement interface on a wall",
        caption: "Position the work directly in the room",
      },
      {
        id: "compare",
        title: "Compare in room",
        text: "Users can place multiple works to compare scale, spacing, and how different pieces sit together before deciding what feels right.",
        mediaType: "image",
        mediaSrc: "/images/Recanvased/Recanvased4.PNG",
        mediaAlt: "ReCanvased multi-artwork AR comparison state",
        caption: "Compare pieces at room scale",
      },
    ],
    caseStudyTextSections: [
      {
        id: "problem",
        title: "The problem",
        text: "Buying art is a high-friction decision. People may like a piece in isolation, but they still struggle to imagine its scale, how it will sit on a wall, or whether it will suit the mood of a room. That uncertainty often leads to hesitation rather than purchase.",
      },
      {
        id: "approach",
        title: "The approach",
        text: "I designed ReCanvased as an end-to-end experience rather than just an artwork marketplace. The browsing app and the AR placement flow were built to work as one journey, so the transition from discovery to decision felt natural rather than bolted on.",
      },
      {
        id: "solution",
        title: "The solution",
        text: "The core idea was to let users move from viewing a piece on a product page to placing it directly on their own wall. By grounding the decision in the actual room, the app could reduce uncertainty and make the purchase feel more confident and informed.",
      },
      {
        id: "outcome",
        title: "The outcome",
        text: "The final project became a clearer proposition about confidence in buying art, not just browsing it. It brought together marketplace browsing, artist listing, and AR visualisation into one coherent system, and it was awarded a Distinction as my final Master’s submission.",
      },
    ],
    gallery: [
      { src: "/images/Recanvased/recanvased-1.mp4", label: "Scroll the gallery to explore everything quickly" },
      { src: "/images/Recanvased/recanvased-2.mp4", label: "Zoom in for a closer look at the details" },
      { src: "/images/Recanvased/recanvased-3.mp4", label: "See each piece in\nyour own space for context" },
      { src: "/images/Recanvased/recanvased-4.mp4", label: "Add multiple artworks at scale to plan a wall" },
    ],
  },
  {
    slug: "lockin",
    title: "Lockin",
    subtitle: "A task manager that protects focus by locking distracting apps",
    heroImage: "/images/Lockin/Homepage%20thumbnail.png",
    detailsVideo: "/images/Lockin/hero.mp4",
    detailsMediaType: "phone",
    pageStyle: "editorial",
    caseStudyDepth: "feature",
    projectDiscipline: "Product design",
    projectServices: "UX/UI · Interaction design · Prototyping",
    editorialStatement: "A task manager that makes focus harder to abandon.",
    outcome: "Lockin connects task completion with phone access, turning distraction into a clear, manageable boundary.",
    editorialPalette: {
      page: "#F2EEEF",
      surface: "#F8F3F7",
      soft: "#E8DEE7",
      primary: "#513B50",
      onPrimary: "#FBF8F5",
      accent: "#D8C9D7",
      onAccent: "#2A2029",
      ink: "#231F22",
      mediaField: "#ECE4EB",
    },
    problem: "To-do lists are easy to ignore when the rest of the phone remains available. Lockin explores how a product can create a useful boundary between unfinished tasks and distracting apps.",
    detailsTitle: "Lockin",
    detailsSubtitle: "Complete the list before you unlock the phone",
    detailsText: "Lockin is a focus app that locks selected apps until the user has completed the tasks on their list. It combines a full calendar, repeat tasks, and a short five-minute break timer to make focused work easier to start, sustain, and return to.",
    caseStudySections: [
      {
        id: "lock-tasks",
        title: "Lock the distracting apps",
        text: "Lockin connects the to-do list to phone access: selected apps stay locked until the required tasks are complete. The constraint is visible and intentional, turning focus into a clear agreement rather than another notification.",
        mediaType: "image",
        frameType: "phone",
        mediaSrc: "/images/Lockin/Lock%20tasks.PNG",
        mediaAlt: "Lockin locked apps and task list",
        caption: "A clear boundary around distraction",
      },
      {
        id: "calendar",
        title: "See the week at a glance",
        text: "A full calendar gives users a broader view of upcoming work, helping them plan beyond the immediate task list and see how small actions fit into the week.",
        mediaType: "image",
        frameType: "phone",
        mediaSrc: "/images/Lockin/Calendar.PNG",
        mediaAlt: "Lockin calendar view",
        caption: "Planning beyond the next task",
      },
      {
        id: "repeat",
        title: "Repeat what matters",
        text: "Repeat tasks support routines without making users recreate the same structure every day. The system is useful for habits, study, and recurring responsibilities.",
        mediaType: "image",
        frameType: "phone",
        mediaSrc: "/images/Lockin/Repeat%20tasks.PNG",
        mediaAlt: "Lockin repeat tasks view",
        caption: "Routines without repetitive setup",
      },
      {
        id: "break",
        title: "Take a five-minute break",
        text: "A short break timer creates a deliberate pause without turning the break into an open invitation to disappear into other apps.",
        mediaType: "image",
        frameType: "phone",
        mediaSrc: "/images/Lockin/Unlock%20for%205mins.PNG",
        mediaAlt: "Lockin five-minute break timer",
        caption: "A deliberate pause before returning to work",
      },
    ],
    caseStudyTextSections: [
      {
        id: "focus-boundary",
        title: "Designing a boundary",
        text: "Phones make distraction easy and unfinished tasks easy to postpone. Lockin makes access conditional, giving the user a simple, visible relationship between what they need to do and what they can open.",
      },
      {
        id: "planning",
        title: "Planning beyond the task",
        text: "The calendar and repeat-task features extend Lockin beyond a single focus session. They help users organise recurring work while keeping the core interaction deliberately simple.",
      },
      {
        id: "recovery",
        title: "A short, useful reset",
        text: "The five-minute break timer creates a controlled release rather than another route into distraction. It gives the user permission to pause, with a clear point at which to return.",
      },
      {
        id: "outcome",
        title: "A calmer relationship with the phone",
        text: "Lockin treats focus as a product relationship rather than a reminder. The result is a tool that helps users make progress by changing what the phone allows them to do next.",
      },
    ],
    gallery: [
      { src: "/images/Lockin/Lock%20tasks.PNG", label: "Lock distracting apps until tasks are complete" },
      { src: "/images/Lockin/Calendar.PNG", label: "Plan the week with a full calendar" },
      { src: "/images/Lockin/Repeat%20tasks.PNG", label: "Repeat tasks for recurring routines" },
      { src: "/images/Lockin/Unlock%20for%205mins.PNG", label: "Take a five-minute break" },
    ],
  },
  {
    slug: "canopy-of-echos",
    title: "Canopy of Echos",
    subtitle: "Best Heritage Narrative Prize · Nanjing Digital Heritage Hackathon",
    heroImage: "/images/CanopyOfEchos/canopy-thumbnail.png",
    detailsHeroImage: "/images/CanopyOfEchos/Demo1.PNG",
    detailsMediaType: "physical",
    pageStyle: "editorial",
    caseStudyDepth: "compact",
    projectDiscipline: "Interactive installation",
    projectServices: "Narrative · Spatial interaction · Prototyping",
    editorialStatement: "Translating fragments of cultural memory into movement, light, and shared space.",
    outcome: "A kinetic heritage installation awarded Best Heritage Narrative at the Nanjing Digital Heritage Hackathon.",
    editorialPalette: {
      page: "#ECE8DF",
      surface: "#F5F1E7",
      soft: "#E2E8E2",
      primary: "#132C2B",
      onPrimary: "#F4F0E5",
      accent: "#D1B56B",
      onAccent: "#172221",
      ink: "#172221",
      mediaField: "#E2E8E2",
    },
    problem: "This is a placeholder problem statement for canopy of echos.",
    detailsTitle: "Canopy of Echos",
    detailsSubtitle: "An interactive sculpture displaying ancient artifacts",
    detailsText: "Canopy of Echos is a kinetic, light-based sculpture created for the 2025 Nanjing Digital Heritage Hackathon. Inspired by fragments of physical and cultural memory, the installation uses moving \"stones\" and responsive lighting to echo the stories of local citizens. The project was awarded the Best Heritage Narrative Prize at the hackathon.",
    caseStudySections: [
      {
        id: "memory",
        title: "Memory made physical",
        text: "Rather than presenting heritage as a fixed archive, the installation turns individual fragments into a collective composition that shifts over time.",
        mediaType: "image",
        frameType: "physical",
        mediaSrc: "/images/CanopyOfEchos/Demo2.png",
        mediaAlt: "Canopy of Echos interactive installation",
        caption: "A changing composition of light and movement",
      },
      {
        id: "narrative",
        title: "An experience without instructions",
        text: "Responsive light and moving forms communicate atmosphere immediately, allowing visitors to understand the emotional premise before reading an explanation.",
        mediaType: "image",
        frameType: "physical",
        mediaSrc: "/images/CanopyOfEchos/CanopyOfEchosAWard.jpg",
        mediaAlt: "Canopy of Echos receiving the Best Heritage Narrative award",
        caption: "Best Heritage Narrative, Nanjing",
      },
    ],
    caseStudyTextSections: [
      {
        id: "brief",
        title: "Making heritage tangible",
        text: "The brief was to create a digital heritage experience that felt connected to lived memory rather than presenting history as a fixed archive. We looked for a form that could be experienced collectively and understood without a long explanation.",
      },
      {
        id: "interaction",
        title: "A responsive sculpture",
        text: "The installation combines moving elements and responsive light to create a physical, changing composition. Each movement acts as a small response to the stories and fragments that informed the work.",
      },
      {
        id: "recognition",
        title: "The outcome",
        text: "Canopy of Echos became an atmospheric way to communicate cultural memory through space, movement, and light. The project was awarded the Best Heritage Narrative Prize at the Nanjing Digital Heritage Hackathon.",
      },
    ],
    gallery: [
      "/images/CanopyOfEchos/CanopyOfEchosAWard.jpg",
      "/images/CanopyOfEchos/IMG_2707.PNG",
      "/images/CanopyOfEchos/Demo2.png",
      "/images/CanopyOfEchos/Screenshot%202025-08-12%20220723.png",
      "/images/CanopyOfEchos/%E6%95%88%E6%9E%9C%E5%9B%BE1%201.png",
    ],
  },
];

const homepageProjectOrder = [
  "panmure-liberum",
  "lockin",
  "learnllama",
  "donkeyjobs",
  "recanvased",
  "canopy-of-echos",
] as const;

export const homepageProjects: Project[] = homepageProjectOrder
  .map((slug) => projects.find((project) => project.slug === slug))
  .filter((project): project is Project => Boolean(project));
